### ISSUE TITLE
Unexpected low download speed

### ISSUE THREAD

**Issue by GH0000000000** [openspeedtest/Speed-Test#58] opened 2022-12-17 20:41 UTC
My PC client and NAS server are connected by 2 x 2.5 Gbps switch. The OpenSpeedTest reports expected upload speed about 2450-2480 Mbps. However, the OpenSpeedTest download speed is always about 1500 Mbps-1800 Mbps (very unstable). Is there any possibility to activate some logs to investigate the issue ? I would like to find "the bottleneck" of download speed using OpenSpeedTest. Possible ?
![NOK LAN WIndows 11 PRO 22H2 Client vs NAS Docker OpenSpeedTest Server](https://user-images.githubusercontent.com/120834662/208265132-745b6ea1-6933-4f93-859f-aabb54266b98.png)

**Comment by openspeedtest** [comment] 2022-12-17 22:52
Which browser? 
1) Try Chrome or Safari
2) Run a speed test from Incognito window or Private window. 
3) Check NIC Driver
4) Turn off QOS in NIC Driver settings
5) Play with different options in NIC Driver settings.

**Comment by GH0000000000** [comment] 2022-12-18 10:13
The previous tests were done on Windows/Chrome.
I have repeated tests on Windows/Chrome + MSEdge in Incognito/Private mode,
no success (the same unexpected results), please review the attachment. The
download test is very unstable and 800-1000 Mbps lower then it should be.
What's more, according to NAS Network Monitor, downloading test on IP LAN2
is presented on... LAN1 (why?). Is it because of some NAS issues or
OpenSpeedTest error ?

The NICs drivers - no update is needed, changing NICs params do not change
the download speed.
Please let me know how download test exactly works, what is file service
used to perform tests ?

sob., 17 gru 2022 o 23:53 OpenSpeedTest™ ***@***.***>
napisał(a):

**Comment by openspeedtest** [comment] 2022-12-18 10:37
Try https://openspeedtest.com/selfhosted-speedtest#Desktop-Mobile-Apps
Run it on your PC and run a speed test on the same PC. It will show the maximum capacity of your system.
When I tested my USB Ethernet without Installing Driver, I had a similar experience. But once I Installed the Driver, everything worked perfectly. Running Antivirus? or URL Filters? They usually intercept all download requests and slow things down. Another important factor is the QoS settings on your router. Did you try transferring large files? Try to isolate the problem. Rule out each device on the network after testing them one by one. 

https://github.com/openspeedtest/Docker-Image this is the dockerFile.
You can play with Nginx Config or logs. But I tested this image on real 10GbE and 30Gbps+ Virtual NIC.
So this will not be a problem. 
Another thing you can do is change the docker network to HOST. 
If your NAS is Busy or SLOW changing the network to HOST might help. 

````
docker pull       openspeedtest/latest:latest
docker stop       openspeedtest
docker rm         openspeedtest
docker run        --detach \
                  --name      openspeedtest \
                  --restart   unless-stopped \
                  --network   host \
                  openspeedtest/latest:latest
````
Also Try UBUNTU LIVE USB + Chrome.

**Comment by GH0000000000** [comment] 2022-12-18 14:08
Thanks for advice. So, you suggest the OpenSpeedTest works correctly, maybe
you are right.
True, in my opinion the culprit is PC NIC driver or PC NIC itself.
My environment is specific, it uses multichannel SMB feature, so sender and
receiver must be configured properly to double the speed of LAN connection.
Single network element works more or less correctly, but multichannel
option is very bizarre.

niedz., 18 gru 2022 o 11:37 OpenSpeedTest™ ***@***.***>
napisał(a):

**Comment by GH0000000000** [comment] 2022-12-18 18:37
BTW: In my opinion OpenSpeedTest done on LAN2 (last attachment) is slightly
inconsistent. The "Download" part is visible on my NAS under LAN1 although
test was run on IP adres of LAN2...

niedz., 18 gru 2022 o 11:37 OpenSpeedTest™ ***@***.***>
napisał(a):

**Comment by openspeedtest** [comment] 2022-12-19 05:11
I never tested a bonded connection. SMB multichannel may work for SMB Transfer. SpeedTest will send multiple XHR Reques to the Server (TCP). I don't know if it will fully utilize both NICs or not in a bonded connection. When we look at upload speed, it is defiantly using both NICs? that is why 2.5Gbps? But I don't know why this is not happening in Download Test.

**Comment by GH0000000000** [comment] 2022-12-19 09:01
Multichannel SMB works only with SMB Transfer. So, there are no
"aggregation" benefits when such environment is used for example to
transfer files by FTP. The same behawior is true for other transfer
protocols. I assume your OpenSpeedTest does not use SMB protocol to praform
speed tests, so each channel should be tested separably. That is why I
prepared first test using IP address of NAS NIC1 and second test using IP
address of NAS NIC2. The OpenSpeedTest works as expected (tests are
performed on LAN1) when I use IP NIC1. However, if I use IP of NIC2, I can
see inconsistency. To understand the issue I performed FTP tests on IP NIC1
and IP NIC2, the answer is... FTP tests ARE consistent, it means that I can
see results (upload/download) exactly on expected LAN. Why OpenSpeedTest
does not work this way, NAS bug ? OpenSpeedTest bug ?

pon., 19 gru 2022 o 06:12 OpenSpeedTest™ ***@***.***>
napisał(a):

**Comment by openspeedtest** [comment] 2022-12-19 09:24
@GH0000000000 This is not a bug in NAS or OpenSpeedTest. I think this is the way it works for TCP when you enable aggregation. Randomly use LAN 1 and 2 for new connections. That is why there are varying results. OpenSpeedTest is just a network benchmarking tool. It will show the available bandwidth at that moment. Many things can affect those numbers. Since I have not played with link aggregation, I don't know how to troubleshoot this issue. Maybe post this in Synology forums or Networking forums. Still, if you are getting expected speeds when using SMB, don't worry about OpenSpeedTest numbers because SMB is working fine.

**Comment by GH0000000000** [comment] 2022-12-19 10:08
There is a difference between aggregation and multichannel. My environment
is multichannel SMB but is not aggregated. All the time I receive the same
results using OpenSpeedTest. On LAN1 is always OK, on LAN2 is always not OK
(so it is not random). BTW, I have similar issue if I use multichannel SMB,
uploading works as expected but downloading is not OK (2x slower as
expected). I will try to contact NAS manufacturer to resolve the issue...

pon., 19 gru 2022 o 10:24 OpenSpeedTest™ ***@***.***>
napisał(a):

**Comment by openspeedtest** [comment] 2022-12-19 11:35
Ok, If you managed to fix this issue, please share those details here. It will help other people who go through this.

**Closed by openspeedtest** 2022-12-19 11:35 UTC
