### ISSUE TITLE
feature: disable google analytics through .env config

### ISSUE THREAD

**Issue by jedi-admin** [openspeedtest/Speed-Test#49] opened 2022-11-06 04:05 UTC
current version of `index.html` has an embedded googletagmanager script. Is there a way to disable it without manually altering existing html file and rebuilding the image? Thanks!

**Comment by openspeedtest** [comment] 2022-11-06 04:38
Good idea, if you know shell scripting or any other way to accomplish this task please send a PR https://github.com/openspeedtest/Docker-Image , now learning go lang and trying to build a CLI-Client for OpenSpeedTest. So i can come back to this only after few months.

**Comment by openspeedtest** [comment] 2022-11-06 04:41
Also we need .env setup for PageTitle, SVG Logo etc.
Basically need shell script? to edit index.html automatically using .env data when deploying the app.

**Comment by jedi-admin** [comment] 2022-11-07 06:06
Thanks for a quick reply, I will take a look and see what I can help with, although I am not a scripting expert by all means :) Perhaps can you tag this issue with "Help needed" maybe someone else would be able to jump in and help.

**Comment by openspeedtest** [comment] 2022-11-07 06:38
Now build an image with the changes you need. We can work on this later.

**Comment by ZPrimed** [comment] 2022-11-10 00:22
This is very privacy-unfriendly. The default installation should not be pinging a google analytics ID.

I was thinking about deploying this system for my non-profit ISP, but once I saw that you were trying to capture data with Google, plus you are submitting all test data back to your own server (where nobody knows what you are doing with that info), I decided against using it.

**Comment by openspeedtest** [comment] 2022-11-10 01:26
Hi, @ZPrimed 

No personally identifiable data is collected, it's Same GA found on almost all websites. 

If you look at GA Code, all we get is page views. Nothing else. 

This is helpful for optimizing the application. 

GA told me last year 500K+ users used IE. 

So that I can optimize this application for those users & It will improve this application. 

Almost all platforms or application collect data like this, including apple, Microsoft, Google etc.  it is to improve the product or service they offer. 

 **_submitting all test data back to your own server (where nobody knows what you are doing with that info)_**

Wrong, we will not submit data back to our servers after each test, it is useless and i don't have the storage or server capacity to process those data. 

Most of the time this application is used in LAN or behind cooperate firewall, Even GA will not work. So how can we send those results back to our server?

if you use **hosted.html** it is just a iFrame with SelfHosted widget. IT WILL send data back to our server and store it on our database. It is a feature for people who don't want to maintain a database. 

By default if you use index.html / default page it will not send data back to server after each test. 

If you click the results after test , it will take you to our website result page. that will **read the values from the URL**. It will not store the result to a database. 


_That is an important feature. Email the result page to an IT Professional for troubleshooting connectivity issues.
So they can see the speed, jitter & ping along with transferred data. So you can find and fix issues by analyzing those values on the result page. Even if you are offline, you can copy the link and view it online later._
https://github.com/openspeedtest/Speed-Test/issues/29

Most people don't need or maintain a database server and need a way to share results. that is why this exists. 

Now you can build your own image https://github.com/openspeedtest/Docker-Image

So that you can remove GA, if you really need.

**Comment by duracell** [comment] 2022-11-11 08:09
> No personally identifiable data is collected, it's Same GA found on almost all websites.

The ip address is rated as a identifiable data regarding to the ECJ. And it is illegal for the owner of the website to send this data to google if the user is from the european union (gdpr violation). As example: Google Font is a huge problem at the moment and people need to pay a lot of fines if the just put it in there website directly from the google server.

**Comment by openspeedtest** [comment] 2022-11-11 09:09
@duracell 

We are not logging IP or any other PII. You can see that from GA code. 

Can you see IP address in GA? i can't. Maybe because GA is loaded from Google Servers. 

Anyway

UA is going EOL within few months.

[Google Analytics 4 properties](https://support.google.com/analytics/answer/9019185?hl=en#zippy=%2Cin-this-article)
In Google Analytics 4, IP anonymization is not necessary since IP addresses are not logged or stored.

I understand the importance of providing options. 
very soon (Early Next Year) we will implement .env config
Now i don't know shell scripting.
 
It will take less than 30 seconds to remove GA and build your own image  https://github.com/openspeedtest/Docker-Image

**Comment by duracell** [comment] 2022-11-11 09:35
> We are not logging IP or any other PII. You can see that from GA code.
> 
> Can you see IP address in GA? i can't. Maybe because GA is loaded from Google Servers.

The problem is that google gets a request and can see the ip address. The same is with google analytics, fonts and every request to 3rd-party (https://rewis.io/urteile/urteil/lhm-20-01-2022-3-o-1749320/). And I know I can build my own image, but I would really recommend to have a default which is legal to use in the eu.

At the end it's your decision and the (legal) responsibility of the users, but this risk only to have google tag data? Is it really worth it?

**Comment by openspeedtest** [comment] 2022-11-15 08:00
Changing the logo, changing the title, removing GA, changing colors, etc., are the most requested features for the docker image. 
Instead of writing a complex shell script to provide an Env variable, users can modify the index.html file or CSS. Then mount the file to the container.

https://forums.docker.com/t/how-to-change-logo-inside-html-file-via-environment-variables/131397/13

**Closed by openspeedtest** 2022-11-15 08:00 UTC
Labels: help wanted

**Comment by openspeedtest** [comment] 2023-01-21 11:35
@jedi-admin @ZPrimed @duracell @C8opmBM 
I lost the joy of looking at the stats. Now, this is a headache. So I am deleting GA from this project and Deleting Issues related to this very soon.

**Comment by openspeedtest** [comment] 2023-01-21 11:39
Removed GA! from the project.

**Comment by openspeedtest** [comment] 2023-01-21 11:48
Updated docker image! Goodbye! 
Thanks..
